bridges = []
persistence_dir = ''
ui_bundles = []
ui_interfaces = []


[[agents]]
id = 'hc-alice'
keystore_file = './alice.keystore'
name = 'alice'
public_address = 'HcScijzE9x3Qjogoz9xOK4NjxFNthmf9br9ow8tN7PUb6djyAoWu5rKuhrsq93i'

[[dnas]]
file = './dist/dna.dna.json'
hash = 'QmWeDETojrXuwDag9iBoCewi22SZyF4JCpyUzjVriuhTsg'
id = 'hc-multisig'

# Alice
[[instances]]
agent = 'hc-alice'
dna = 'hc-multisig'
id = 'alice-instance'

[instances.storage]
type = 'memory'

[[interfaces]]
admin = true
id = 'alice-interface'

[[interfaces.instances]]
id = 'alice-instance'

[interfaces.driver]
port = 8888
type = 'websocket'


[logger]
state_dump = true
type = 'debug'
[[logger.rules.rules]]
    color = "red"
    exclude = false
    pattern = "^err/"

    [[logger.rules.rules]]
    color = "white"
    exclude = false
    pattern = "^debug/dna"

    [[logger.rules.rules]]
    exclude = true
    pattern = "^debug/reduce"

    [[logger.rules.rules]]
    exclude = false
    pattern = ".*"

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false